version: '3.9'

services:
  model:
    image: registry-vpc.cn-shanghai.aliyuncs.com/gaibu/sd-download:1.0.0
    volumes:
      - share-data:/data
    entrypoint: [ "sh", "-c","nohup ping -i 1000 127.0.0.1" ]
  auto:
    ports:
      - "${WEBUI_PORT:-7860}:7860"
    volumes:
      - share-data:/data
      - ./output:/output
    stop_signal: SIGKILL
    tty: true
    image: registry-vpc.cn-shanghai.aliyuncs.com/gaibu/sd-auto:1.0.0
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    runtime: nvidia  # 添加这一行
volumes:
  share-data:
