name: Build Images

on:
  push:
    branches:
      - master
      - 1.0.0
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      max-parallel: 3
      matrix:
        profile:
          - sd_pre
#          - sd_second
        include:
          - profile: auto
            dockertag: "sd-auto:54"
            dockerhubtag: "sd-auto"
          - profile: download
            dockertag: "webui-docker-download:latest"
            dockerhubtag: "sd-download"
          - profile: sd_pre
            dockertag: "sd-pre:54"
            dockerhubtag: "sd-pre"
          - profile: sd_second
            dockertag: "sd-second:54"
            dockerhubtag: "sd-second"
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - name: Git checkout the code.
        uses: actions/checkout@v3
      - name: Build the docker images.
        run: docker compose --profile ${{ matrix.profile }} build --progress plain

      - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: vars.DOCKERHUB_USERNAME
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tags docker images latest
        if: vars.DOCKERHUB_USERNAME
        run: docker tag ${{matrix.dockertag}} ${{vars.DOCKERHUB_USERNAME}}/${{matrix.dockerhubtag}}:1.0.0
      - name: Tags docker images with sha
        if: vars.DOCKERHUB_USERNAME
        run: docker tag ${{matrix.dockertag}} ${{vars.DOCKERHUB_USERNAME}}/${{matrix.dockerhubtag}}:${SHORT_SHA}
      - name: push images to docker hub
        if: vars.DOCKERHUB_USERNAME
        run: docker push --all-tags ${{vars.DOCKERHUB_USERNAME}}/${{matrix.dockerhubtag}}
